"""empty message

Revision ID: 91707d274084
Revises: 4e9eac1c29ca
Create Date: 2020-01-16 16:51:48.060413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91707d274084'
down_revision = '4e9eac1c29ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(length=120), nullable=True),
    sa.Column('artist_name', sa.String(length=120), nullable=True),
    sa.Column('artist_image_link', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_table('Show')
    # ### end Alembic commands ###
